trigger: none
pr: none

schedules:
- cron: '0 0 1 * *'
  always: true
  branches:
    include:
    - main

pool: sonicbld

jobs:
- job: update
  variables:
  timeoutInMinutes: 120
  - group: SONICBLD
  steps:
  - checkout: self
    clean: true
    path: s
  - bash: |
      set -ex
      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
      sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      sudo apt update
      sudo apt install gh jq -y

      echo $TOKEN | gh auth login --with-token
    env:
      TOKEN: $(GH_TOKEN)
    displayName: setup env
  - bash: |
      set -ex
      git config user.email 'sonicbld@microsoft.com'
      git config user.name 'Sonic Automation'

      cd sii_hld
      ./dump_hld_data.sh
      git add dash_hld.csv sai_hld.csv sonic_hld.csv
      cd ..

      cd sii_issue
      ./issues_dump.sh
      git add issues.json
      cd ..

      cd sii_testplan_hld
      ./generate_testplan_hld_data.sh
      git add sonic-mgmt_hld.csv
      cd ..

      cd sii_pr_review
      for repo in $(cat repos)
      do
        current=$(date -I)
        year=${current:0:4}
        year1=$(( $year -1 ))
        ./pr_dump.sh -y "$year1 $year" -r $repo
        ./pr_dump.sh -y "$year1 $year" -t reviews -r $repo
      done
      cd ..

      cd sii_test_pr_review
      current=$(date -I)
      year=${current:0:4}
      year1=$(( $year -1 ))
      ./pr_dump.sh -y "$year1 $year"
      cd ..

      git diff --cached
      git diff
    displayName: dump data

